-- 0007_old_namor.sql
-- Generated by drizzle-kit against a DB that already has 0003–0006 applied.
-- All statements are guarded with IF NOT EXISTS / DO blocks to be idempotent.

CREATE SCHEMA IF NOT EXISTS "metrics";
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "blurb_cache" (
	"site_cache_id" uuid NOT NULL,
	"mood_id" text NOT NULL,
	"blurb" text NOT NULL,
	"model" text NOT NULL,
	"generated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "blurb_cache_site_cache_id_mood_id_pk" PRIMARY KEY("site_cache_id","mood_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "ingest_attempts" (
	"url_hash" text PRIMARY KEY NOT NULL,
	"url" text NOT NULL,
	"first_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_try_at" timestamp with time zone,
	"attempts" integer DEFAULT 0 NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"reject_reason" text,
	"source" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "metrics"."agent_task_events" (
	"id" integer PRIMARY KEY NOT NULL,
	"ts" timestamp with time zone NOT NULL,
	"trace_id" text,
	"worker_id" text NOT NULL,
	"task_name" text NOT NULL,
	"queue" text,
	"status" text NOT NULL,
	"duration_ms" integer,
	"retries" smallint DEFAULT 0 NOT NULL,
	"error_type" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "metrics"."daily_llm_cost" (
	"day" timestamp,
	"model" text,
	"provider" text,
	"call_type" text,
	"calls" integer,
	"total_prompt_tokens" integer,
	"total_completion_tokens" integer,
	"total_cost_usd" numeric,
	"users_charged" integer
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "metrics"."daily_summary" (
	"day" timestamp,
	"daily_sessions" integer,
	"daily_users" integer,
	"total_requests" integer,
	"avg_response_ms" numeric,
	"p95_response_ms" numeric,
	"errors_5xx" integer,
	"countries" integer
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "metrics"."llm_cost_events" (
	"id" integer PRIMARY KEY NOT NULL,
	"ts" timestamp with time zone NOT NULL,
	"trace_id" text,
	"worker_id" text NOT NULL,
	"user_id" text,
	"task_type" text NOT NULL,
	"call_type" text NOT NULL,
	"model" text NOT NULL,
	"provider" text NOT NULL,
	"prompt_tokens" integer NOT NULL,
	"completion_tokens" integer,
	"estimated_cost_usd" numeric(10, 6) DEFAULT '0' NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "metrics"."page_events" (
	"id" integer NOT NULL,
	"ts" timestamp with time zone NOT NULL,
	"trace_id" text,
	"session_id" text NOT NULL,
	"user_id" text,
	"source" text DEFAULT 'api' NOT NULL,
	"worker_id" text,
	"path" text NOT NULL,
	"method" text NOT NULL,
	"status" smallint NOT NULL,
	"response_ms" integer NOT NULL,
	"referrer_host" text,
	"country" text,
	"device_class" text,
	"app_version" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "moods" (
	"id" text PRIMARY KEY NOT NULL,
	"display_name" text NOT NULL,
	"seed_prompt" text NOT NULL,
	"embedding" vector(1536) NOT NULL,
	"category_priors" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "site_cache" ADD COLUMN IF NOT EXISTS "mood_affinities" jsonb DEFAULT '{}'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "site_cache" ADD COLUMN IF NOT EXISTS "language" text DEFAULT 'en' NOT NULL;--> statement-breakpoint
ALTER TABLE "site_cache" ADD COLUMN IF NOT EXISTS "content_type" text DEFAULT 'article' NOT NULL;--> statement-breakpoint
ALTER TABLE "site_cache" ADD COLUMN IF NOT EXISTS "popularity" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "site_cache" ADD COLUMN IF NOT EXISTS "love_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "site_cache" ADD COLUMN IF NOT EXISTS "skip_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "site_cache" ADD COLUMN IF NOT EXISTS "block_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "site_cache" ADD COLUMN IF NOT EXISTS "last_shown_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "site_cache" ADD COLUMN IF NOT EXISTS "ingested_at" timestamp with time zone DEFAULT now();--> statement-breakpoint
ALTER TABLE "site_cache" ADD COLUMN IF NOT EXISTS "rescore_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "site_cache" ADD COLUMN IF NOT EXISTS "status" text DEFAULT 'ready' NOT NULL;--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "blurb_cache" ADD CONSTRAINT "blurb_cache_site_cache_id_site_cache_id_fk" FOREIGN KEY ("site_cache_id") REFERENCES "public"."site_cache"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "blurb_cache" ADD CONSTRAINT "blurb_cache_mood_id_moods_id_fk" FOREIGN KEY ("mood_id") REFERENCES "public"."moods"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_blurb_cache_site" ON "blurb_cache" USING btree ("site_cache_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_ingest_attempts_status" ON "ingest_attempts" USING btree ("status");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "idx_feedback_session_site" ON "feedback" USING btree ("session_id","site_cache_id");